# Generated by Django 6.1.1 on 2026-09-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_message_at', models.DateTimeField()),
                ('interval_minutes', models.PositiveIntegerField(default=1440)),
                ('max_followups', models.PositiveIntegerField(default=3)),
                ('followups_sent', models.PositiveIntegerField(default=0)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('paused', models.BooleanField(default=False)),
                ('customer_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer')),
            ],
        ),
    ]
