# Generated by Django 6.1.1 on 2026-09-21 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_message_user(apps, schema_editor):
    Message = apps.get_model("messaging", "Message")

    for message in Message.objects.select_related("customer").all():
        if message.user_id is None and message.customer:
            message.user_id = message.customer.user_id
            message.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('general', 'General'), ('followup', 'Follow-up'), ('sales', 'Sales'), ('reminder', 'Reminder'), ('check_in', 'Check-in'), ('re_engagement', 'Re-engagement')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='tone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.RunPython(
            backfill_message_user,
            migrations.RunPython.noop,
        ),
    ]
